[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build -w apps/api"

[deploy]
startCommand = "node apps/api/dist/main"
preDeployCommand = "npx prisma migrate deploy --schema=apps/api/prisma/schema.prisma"
