[build]
builder = "NIXPACKS"
buildCommand = "npm install --include=dev && cd apps/api && npx prisma generate && npx nest build"

[deploy]
startCommand = "node apps/api/dist/src/main"
preDeployCommand = "npx prisma migrate deploy --schema=apps/api/prisma/schema.prisma"
